### PR TITLE
 Change for links in header and footer

### PR DESCRIPTION
**Pull request by nidalaa**
- change 'Forum' title in footer section to 'Community'
- change 'Rravel buddies and for sale' link to 'Travel Companions' in footer
- reorder links in 'Community' section in footer
- remove '/airport-transfers' link from global header Bookings section

Details: https://trello.com/c/fNRcOqdf/1550-as-john-i-want-changes-in-global-footer

### CODE REVIEW

**Comment by nidalaa** [comment]
We need to merge the same changes in rizzo next first https://github.com/lonelyplanet/rizzo-next/pull/837

**Comment by WunderBart** [comment]
What about this one? https://github.com/lonelyplanet/rizzo/blob/278b0e601e6869fb442e89d9326c4a2ac228b59f/app/data/layouts/primary_nav.yml#L118

**Comment by nidalaa** [comment]
@ is it a part of the footer?

**Comment by nidalaa** [comment]
@WunderBart is it a part of the footer? The task was to change the text only in footer.

**Comment by WunderBart** [comment]
No, it's primary nav. I know we've disabled it probably everywhere, but it still doesn't make sense to have `Thorn Tree` there and `Community` in the footer, IMO.

**Comment by nidalaa** [comment]
Sorry, that was the requirement: `Community` in the footer, and `Thorn Tree` in  avatar drop down menu.

**Pull request merged**
