### PR TITLE
Add a few missing weather icons

### PR DESCRIPTION
**Pull request by remybach**
Mostly copies of existing ones.

### CODE REVIEW

**Comment by stevebrownlee** [comment]
Looks good :+1:

**Comment by chee** [comment]
did you run `grunt icon` to optiminimise these?

**Comment by remybach** [comment]
Oops... no, I didn't. I'll do that now and push up to `master`.

**Comment by stevebrownlee** [comment]
I learned something today!  Never heard of grunt icon before

**Comment by jcreamer898** [comment]
Me too. Nice.

**Pull request merged**
