### PR TITLE
Add Array.prototype.indexOf polyfill

### PR DESCRIPTION
**Pull request by WunderBart**
Source: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

### CODE REVIEW

**Comment by stevebrownlee** [comment]
Hey @WunderBart what is this needed for?

**Comment by WunderBart** [comment]
Currently, in Community we encounter JS errors in <IE9 whenever we use `indexOf` on Array object. This causes some crucial functionality (like abuse reporting) not to work as intended.

**Comment by stevebrownlee** [comment]
Ah, ok. :shipit:

**Comment by WunderBart** [comment]
Merged with https://github.com/lonelyplanet/rizzo/pull/1312. Closing.

**Pull request closed without merging**
