### PR TITLE
add npm shrinkwrap

### PR DESCRIPTION
**Pull request by chee**
https://trello.com/c/MzRvYm2i/199-add-an-npm-shrinkwrap-file

### CODE REVIEW

**Comment by Ianfeather** [comment]
How is this generated and does it change workflow at all for other people? Is it just a case of checking this file in when there's an npm bump?

Looks good though.

**Comment by chee** [comment]
typed `npm shrinkwrap`

**Comment by Ianfeather** [comment]
Solid

**Comment by Ianfeather** [comment]
+1

**Pull request merged**
