### PR TITLE
Remove .row-- prefixes from elements that arent in the list

### PR DESCRIPTION
**Pull request by chee**
warning: will break apps

https://github.com/lonelyplanet/waldorf/pull/1808/files

### CODE REVIEW

**Comment by chee** [comment]
@lonelyplanet/ui should row--faux-banner be left? and row--breadcrumbs? they both are used in a zillion places

**Comment by Ianfeather** [comment]
I'm no longer convinced there's value to this. What do you think? It would be almost easier to just add them to that page showing the page layout. This was proposed as a solution to fix the confusion around how the `rows` in rizzo "work" which I don't feel is much of a problem and certainly hasn't appeared as a problem since. 

This would open up more questions too because changing `.row--image` to `.image` leaves it a bit too unspecific and may cause clashes.

I'm of the opinion it's not worth it, but open to persuasion.

**Comment by chee** [comment]
I am not convinced of it enough to persuade. @lonelyplanet/ui anybody want to persuade?

**Comment by chee** [comment]
closing

**Pull request closed without merging**
