### PR TITLE
Amends from Ruby `2.2.0` environment

### PR DESCRIPTION
**Pull request by marckysharky**

### CODE REVIEW

**Comment by remybach** [comment]
Seems ok to me :+1:

**Comment by marckysharky** [comment]
The `data` attribute was duplicated, so I merged the options together.

If someone has any advice on an alternative implementation, please let me know.

**Comment by remybach** [comment]
Not aside from wanting to have this kind of messy code in a presenter or something rather, but that's not within Rizzo's current capabilities and a discussion for another day I reckon.

**Comment by stevebrownlee** [comment]
Looks like there's a cage match in store between this PR and https://github.com/lonelyplanet/rizzo/pull/1246. Any more thoughts on this?

**Comment by robuye** [comment]
closing in favor of #1246

**Pull request closed without merging**
