### PR TITLE
If rails 4

### PR DESCRIPTION
**Pull request by Ianfeather**
Upgrades Rizzo to rails 4

Also:
- Fixes the v slow asset precompilation
- Fixes the broken pages in the style guide: picture, price-label
- Deals with this `transition: all` card https://trello.com/c/zKp4N0lm/156-remove-the-references-to-transition-all-in-favour-of-transitioning-only-on-the-properties-we-mean

image

image

### CODE REVIEW

**Comment by chee** [comment]
going to check this branch out to see if it even starts up

**Comment by Ianfeather** [comment]
That could be this PR's achilles heel

**Comment by chee** [comment]
when we merge this we can delete the requirejs branch?

**Comment by Ianfeather** [comment]
No other apps appear to be using it. I would favour deleting it for sure

**Comment by chee** [comment]
`:D`

**Comment by chee** [comment]
it runs and passes tests and doesn't have anything crazy in it. plush swan :+1:

**Comment by Ianfeather** [comment]
Gracias

**Pull request merged**
