### PR TITLE
updating subnav and bumping rizzo-next

### PR DESCRIPTION
**Pull request by nicrocs**

### CODE REVIEW

**Comment by jcreamer898** [comment]
Actually, believe it or not, don't actually bump rizzo-next yet. :)

**Comment by jcreamer898** [comment]
There are a bunch of changes that happened which will bork the global nav if we merge that bump.

**Comment by jcreamer898** [comment]
Eventually we'll get around to bumping it with this PR... https://github.com/lonelyplanet/rizzo/tree/jc-remove-split

**Comment by nicrocs** [comment]
ok, I'll revert

**Comment by jcreamer898** [comment]
👍

**Pull request merged**
