### PR TITLE
fix: Bump rizzo next

### PR DESCRIPTION
**Pull request by jcreamer898**

### CODE REVIEW

**Comment by nidalaa** [comment]
- when I am logged in with production luna:
  - [x] correct avatar
  - [x] `Settings` link goes to Luna's show#profile in Luna 
  - [x]  Sign out link signs me out from Luna
  
- when I am logged in with production dotcom-connect:
  - [x] correct avatar
  - [ ] `Settings link tries to go to edit#profile in new profiles but by adding` `/profile/1aaa4b44-54a3-4ef7-b22f-4ade59737078/edit` at the end of current url(which is http://local.qa.lonelyplanet.com:3000/profile/1aaa4b44-54a3-4ef7-b22f-4ade59737078/edit in my case)  **
  - [x] Sign out link signs me out from dotcom-connect
  
- when I am not logged in and no varian cookie present
  - [x] Sign in link goes to https://auth.lonelyplanet.com/users/sign_in
  
- when I am not logged in and variant cookie is present
  - [x] Sign in link goes to https://connect.lonelyplanet.com/oauth/authorize?scope=openid&response_type=code&client_id=foymu5r6sscxe&redirect_uri=https%3A%2F%2Fconnect.lonelyplanet.com%2Fsso

So, 👍  from my but I would just make sure that `Settings link`inn case of production TT wouldn’t not link ti invalid place like https://www.lonelyplanet.com/thorntree/profile/nidalia.

**Comment by jcreamer898** [comment]
@nidalaa for the `Settings link` thing, this is intentional so that it'll work depending on the environment you're running dotcom-profiles in. :+1:

**Comment by nidalaa** [comment]
@jcreamer898 awesome 👍 I am gonna give it a try in production :)

**Comment by jcreamer898** [comment]
YAAAAASSSSSSS

**Comment by thomasthesecond** [comment]
We'll wait for https://github.com/lonelyplanet/rizzo-next/pull/718 and then we'll have to update the version to 0.22.0

**Pull request merged**
