### PR TITLE
Bart new feed popups

### PR DESCRIPTION
**Pull request by WunderBart**
**This PR is mainly for the "Your Feed Popups" feature.** 

The feature was requested by TT users, so it's disabled by default in all other apps. To enable it, you need to add `window.lp.userFeed.popups = true` property to your app.
All the other display settings are managed through TT [forum settings](https://www.lonelyplanet.com/thorntree/forums/settings) (will be available after [this](https://github.com/lonelyplanet/community/pull/2414) gets merged).

`Desktop`

user feed popups 2

`Mobile` (popup is full width and the close button is always visible)

user feed popups mobile

**Note:**
Feed is fetched each 15 seconds, so it's extremely unlikely to get more than 1-2 notifications at once. Just wanted to show dat cool stacking animation :]

### CODE REVIEW

**Comment by jcreamer898** [comment]
This makes me really wish we had some kind of WebSocket service or something. That whole check every 15 seconds thing makes me sad. Lol.

Other than that though, the code rocks. Excellent job.

**Comment by jcreamer898** [comment]
One thing that would be nice if you get a chance would be to add a little bit of info on this component into the rizzo documentation stuff. Can be in a separate PR though if you want.

**Comment by WunderBart** [comment]
Ad WebSockets - we've decided to go with simple poll since the feed is disabled for mobile devices. The only scenario where it keeps fetching is when user decides to have pop-ups enabled, but they are currently TT-exclusive. For the rest of LP apps nothing will change.

Ad documentation update - I will definitely add some info there, but it will be in separate PR. Tomorrow :D

**Comment by jcreamer898** [comment]
Rock on dude. Love it.

**Comment by WunderBart** [comment]
Thanks :smile:

**Comment by nidalaa** [comment]
At one beautiful day :tm: we will go with WebSocets...

Regarding current soultions- checked in community, works like a charm :+1:

**Comment by WunderBart** [comment]
(Rabased it all to keep history clean. Nothing has changed)

**Pull request merged**
