### PR TITLE
Adding a possibility to create links with set target in nav items

### PR DESCRIPTION
**Pull request by nidalaa**
@WunderBart what do you think?

### CODE REVIEW

**Comment by WunderBart** [comment]
Could you present some use case for this?

**Comment by stevebrownlee** [comment]
@nidalaa What is the purpose of this change? Can you provide a brief description of what you are trying to accomplish? Thanks.

**Comment by nidalaa** [comment]
@stevebrownlee  The main change is adding `target: item[:target]`. Thanks to this when I am creating a list of nav items, I can set target to `_blank`, so the link will be open in new tab. This is a main reason of this p/r(rest changes are just about attribute order).

**Comment by stevebrownlee** [comment]
Well that sounds like a great addition.  How do I test it?

**Comment by nidalaa** [comment]
@stevebrownlee  I think that the easiest way is to add:
`target: "_blank"` to secondary items in style guide application(https://github.com/lonelyplanet/rizzo/blob/master/app/lib/rizzo_app.rb#L35).

**Comment by stevebrownlee** [comment]
Works as described. :+1:

**Pull request merged**
