### PR TITLE
[DO NOT MERGE]Add slide-in menu for User Feed component

### PR DESCRIPTION
**Pull request by WunderBart**
Requires `window.lp.userFeed.slideIn` argument to initialize. 

@nidalaa clicky click plox? :clap: :dancers:

### CODE REVIEW

**Comment by nidalaa** [comment]
Under the mods testing in community.

**Comment by nidalaa** [comment]
Tested in community :+1: 
Let's merge it finally @WunderBart

**Comment by WunderBart** [comment]
DO IT

**Comment by WunderBart** [comment]
:trolleybus:

**Pull request merged**
