### PR TITLE
Add select multiple component

### PR DESCRIPTION
**Pull request by WunderBart**
screenshot 2015-07-01 13 33 46
screenshot 2015-07-01 13 33 59

### CODE REVIEW

**Comment by robuye** [comment]
one jasmine spec has failed and you should update the styleguide.

**Comment by robuye** [comment]
does it allow blank?

**Comment by WunderBart** [comment]
Yep.

**Comment by robuye** [comment]
:+1:

**Comment by WunderBart** [comment]
You mean empty array, right?

**Comment by robuye** [comment]
no, I mean to allow user to choose nothing.

**Comment by robuye** [comment]
:+1:

**Pull request merged**
