### PR TITLE
Bump requirejs-rails & sprockets to latest releases

### PR DESCRIPTION
**Pull request by WunderBart**

### CODE REVIEW

**Comment by WunderBart** [comment]
@jcreamer898, we did the same update in Community few days ago - it went pretty smooth. Shall we :shipit:? /cc @nidalaa

**Comment by nidalaa** [comment]
@WunderBart  "pretty smooth", it should be  ok :tm: , however in community a small change in jenkins config was required. It would be good to merge it under special jenkins the control.

**Comment by jcreamer898** [comment]
Works for me.

**Comment by jcreamer898** [comment]
What could possibly go wrong? :tm:

**Comment by nidalaa** [comment]
@jcreamer898 because you said *that* sentence: in case of any problems it will be your fault! :D

**Pull request merged**
